<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { ButtonProps } from ".."
	import { Button } from 'sk-clib';
	import { getRadioHorizontalCtx } from '../ctx.svelte';
    
    let {
        children,
        class: className,
        buttonClass = $bindable('dark:hover:bg-gray-100 hover:bg-[#3E3E55] hover:text-white dark:hover:text-black cursor-pointer block px-4 py-2 text-sm text-gray-700 w-full text-left'),
        href = $bindable(undefined),
        onclick = $bindable(() => {}),
        ...rest
    }: ButtonProps = $props();

    // --- Context ---
    const {_class} = getRadioHorizontalCtx()

    function route_to() {
        if (!href) return;
        window.location.href = href
    }

    $effect(() => {
        if (href) {
            onclick = route_to
        }
    })

    // Setup Button's class
    let buttonCls = $derived(cn(buttonClass, _class.buttonClass, _class.classButton, className));

</script>

<Button class={ buttonCls } {...rest} {onclick}>
    {@render children?.()}
</Button>

<!--@component
    Generated by SvelteForge🔥

    @file DropdownButton.svelte
    @description
    A button inside a dropdown menu, used within `Dropdown.Content` or `Dropdown.Trigger`. It automatically inherits styling
    from the parent dropdown via context, and optionally supports linking via the `href` prop.

    @props
    Extends `HTMLButtonAttributes`, so any native button props are allowed. Key props include:
    - `buttonClass`: Local styling for this button instance.
    - `class`: Native Svelte `class` merged in as well.
    - `href`: Optional string — if present, clicking the button will navigate to the given URL.
    - `onclick`: Optional event handler, overridden if `href` is present.

    @context
    Pulls shared class context via `getRadioHorizontalCtx()`:
    - `_class.buttonClass`, `_class.classButton`: Default and user-provided styling inherited from `Dropdown.Menu`.

    @behavior
    If `href` is provided, clicking the button performs a client-side redirect. Otherwise, `onclick` fires normally.

    @rendered
    Renders a `<Button>` from `sk-clib`, passing the merged class and all other props.

    @usage
    Use this component for both internal navigation and actions:

    ```svelte
    <Dropdown.Button href="/profile">Profile</Dropdown.Button>
    <Dropdown.Button onclick={logout}>Logout</Dropdown.Button>
    ```
-->