<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { Props } from "..";
	import { Header } from 'sk-clib';
    
    let {
        children,
        class: className,
        headerClass = $bindable('dark:text-white'),
        ...rest
    }: Props = $props();


    // Setup Header's class
    let headerCls = $state(cn(headerClass, className));
    $effect(() => {
        headerCls = cn(headerClass, className)
    })

</script>

<Header class={ headerCls } {...rest}>
    {@render children?.()}
</Header>

<!--@component
    Generated by SvelteForge🔥

    sk-clib header wrapper.
-->

