<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { Props } from "..";
    import { Text } from "sk-clib";
    
    let {
        children,
        class: className,
        textClass = $bindable('dark:text-white text-gray-500'),
        ...rest
    }: Props = $props();


    // Setup Text's class
    let textCls = $state(cn(textClass, className));
    $effect(() => {
        textCls = cn(textClass, className)
    })


</script>

<Text class={ textCls } {...rest}>
    {@render children?.()}
</Text>


<!--@component
    Generated by SvelteForge🔥

    sk-clib text wrapper
-->

