# Domain or IP Address
host: "dev.local"

backend:
  uvicorn_config:
    # Backend Port, Don't mess with this unless you plan on re-doing the docker config
    port: 4000

    # Host ip address for backend, also don't mess with ths
    host: "0.0.0.0"

    # Prevent logging
    log_level: "error"

frontend:
  API_BASE: http://backend:4000/ # Route the frontend uses for api requests in the server

database:
  username: "mongo_user"
  password: "mongo_password"