# Domain or IP Address
host: "dev.local"

backend:
  uvicorn_config:
    # Backend Port, Don't mess with this unless you plan on re-doing the docker config
    port: 4000

    # Host ip address for backend, also don't mess with ths
    host: "0.0.0.0"

    # Prevent logging
    log_level: "error"

frontend:
  API_BASE: http://backend:4000/ # Route the frontend uses for api requests in the server

database:
  username: "mongo_user"
  password: "mongo_password"
  auth_db: "db_name"

router:
  extra_subdomains: # Extra subdomains to be added to the router's cert generation
    - api

  config_file: "packages/router/Caddyfile" # Caddy config file, passed through the docker container
  template_file: "packages/router/Caddyfile.template" # Regular caddy template file
  dev_template_file: "packages/router/Caddyfile.dev.template" # Template file used if dev flag is true

# Tool specific configurations
tool:

  # Comment used in the SSH generation
  ssh_identity: "project_tool@sqmdc-template"

  # SSH file output, relative to project root
  ssh_file_out: "packages/tools/ssh/id_ed25519"