<script lang="ts">

    
    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { TriggerProps } from ".."
	import { onMount } from 'svelte';
	import { getDropdownCtx } from '../ctx.svelte';
    
    let {
        children,
        class: className,
        triggerClass = $bindable('')
    }: TriggerProps = $props();

    // --- References ---
    let trigger_reference: HTMLDivElement | undefined = $state<HTMLDivElement | undefined>(undefined); 

    // --- Context ---
    const { _state, toggle, set } = getDropdownCtx()

    function toggle_menu() {
        // Toggle State
        toggle();
    }

    function click_outside(event: MouseEvent) {
        
        // Use also trigger_reference
        const menu_ref = _state.content_reference
        const trigger_ref = trigger_reference

        if (
            menu_ref &&
            trigger_ref &&
            !menu_ref.contains(event.target as Node) &&
            !trigger_ref.contains(event.target as Node)
        ) {
            set(false); // Close dropdown
        }
    }

    onMount(() => {
        document.addEventListener("click", click_outside)
        return () => {
            document.removeEventListener("click", click_outside)
        }
    })

    // Setup Trigger's class
    let triggerCls = $derived(cn(triggerClass, className));

</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<!-- svelte-ignore a11y_click_events_have_key_events -->
<div bind:this={trigger_reference} class={ triggerCls } onclick={toggle_menu}>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥

    @file DropdownTrigger.svelte
    @description
    A clickable wrapper that toggles the visibility of the dropdown. This component is used inside 
    `Dropdown.Menu` as the trigger element, typically wrapping a `Dropdown.Button`. It sets up click handling,
    styling, and dropdown visibility control using context.

    @props
    Extends `HTMLAttributes<HTMLDivElement>`, so you can pass typical `div` attributes. Main prop usage includes:

    - `triggerClass`: Optional class used to style the trigger wrapper (`<div>`) directly.
    - `class`: Native Svelte `class` that gets merged with `triggerClass`.

    @context
    Pulls from the dropdown context via `getDropdownCtx()`:
    - `_state.active`: Tracks open/closed status.
    - `_state.content_reference`: Used for outside click detection.
    - `toggle()`: Toggles the open/closed state.
    - `set(value: boolean)`: Explicitly opens or closes the dropdown.

    @behavior
    - Clicking the trigger toggles the dropdown (`toggle()`).
    - Clicking outside both the trigger and the content automatically closes the dropdown (`set(false)`).
    - Cleans up its event listener on unmount.

    @rendered
    Renders a single `<div>` element with:
    - `bind:this={trigger_reference}` to track the trigger element for click-outside logic.
    - `class={triggerCls}` which merges `triggerClass` and `class`.
    - `onclick={toggle_menu}` to toggle dropdown state.
    - Renders any children passed in via `{@render children?.()}`.

    @usage
    Use this component inside a `Dropdown.Menu` to wrap your trigger button:

    ```svelte
    <Dropdown.Menu>
        <Dropdown.Trigger>
            <Dropdown.Button>Toggle Menu</Dropdown.Button>
        </Dropdown.Trigger>

        <Dropdown.Content>
            // Content Here
        </Dropdown.Content>
    </Dropdown.Menu>
    ```

    This component handles dropdown toggling and closing on outside click automatically.
-->