<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { Props } from ".."
	import { setDropdownCtx } from '../ctx.svelte';
    
    let {
        children,
        class: className,

        // Default Classes
        dropdownClass = $bindable(''),
        buttonClass = $bindable('px-4 py-2 bg-[#F0F0F2] dark:bg-[#3E3E55] dark:text-white text-sm font-medium rounded-none'),
        contentClass = $bindable('flex items-center justify-center overflow-hidden'),
        dividerClass = $bindable('bg-black/10'),

        // User Defined Classes
        classButton = $bindable(''),
        classContent = $bindable(''),
        classDivider = $bindable(''),
        
        ...rest
    }: Props = $props();


    // Setup Dropdown's class
    let dropdownCls = $state(cn(dropdownClass, className));
    $effect(() => {
        dropdownCls = cn(dropdownClass, className)
    })

    // Set Context Here
    const {_class} = setDropdownCtx()
    _class.buttonClass = buttonClass
    _class.contentClass = contentClass
    _class.dividerClass = dividerClass
    _class.classButton = classButton
    _class.classContent = classContent
    _class.classDivider = classDivider

</script>

<div class={ dropdownCls } {...rest}>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥

    @file Dropdown.svelte
    @description
    The root dropdown wrapper used via `Dropdown.Menu`, which manages and distributes class-based styling
    to its subcomponents using Svelte 5's context and `$bindable` syntax. This enables full customization
    while keeping subcomponent APIs minimal and declarative.

    @props
    Extends `HTMLAttributes<HTMLDivElement>`, so you can pass any native HTML `div` attributes.

    ### Core Class Props:
    - `dropdownClass`: Styling for the outer dropdown wrapper.
    - `buttonClass`: Default styling applied to all dropdown buttons (e.g., inside `<Dropdown.Trigger>`).
    - `contentClass`: Styling for the dropdown content container.
    - `dividerClass`: Styling for any `Dropdown.Divider` element.

    ### User-Overridable Class Props:
    These allow injecting *extra* styling on top of the defaults:
    - `classButton`: Additional classes for `<Dropdown.Button>`.
    - `classContent`: Additional classes for `<Dropdown.Content>`.
    - `classDivider`: Additional classes for `<Dropdown.Divider>`.

    These props are bindable and reactive. They are injected via `setDropdownCtx()` and accessed
    by all subcomponents, ensuring consistency without tight coupling.

    @context
    Sets a shared dropdown context which exposes all class-related styling. Each subcomponent (Trigger, Button, Content, Divider)
    pulls from this context so they stay in sync with the parent dropdown configuration.

    @rendered
    A single wrapper `<div>` element with the merged `class` and `dropdownClass`, containing all slotted children.

    @usage
    Use `Dropdown.Menu` as the root, then nest the other subcomponents inside:

    ```svelte
    <Dropdown.Menu classButton="bg-white text-black">
        <Dropdown.Trigger>
            <Dropdown.Button>Open Dropdown</Dropdown.Button>
        </Dropdown.Trigger>

        <Dropdown.Content>
            <Dropdown.Button href="/account">Go to Account</Dropdown.Button>
            <hr />
            <Dropdown.Button on:click={callback}>Click me</Dropdown.Button>
            <Dropdown.Divider />
            <Dropdown.Button>Just a Button</Dropdown.Button>
        </Dropdown.Content>
    </Dropdown.Menu>
    ```

    This structure allows you to fully customize how the dropdown looks and behaves, while still being
    modular and clean to read.
-->