<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { ContentProps } from ".."
	import { getDropdownCtx } from '../ctx.svelte';
    
    let {
        children,
        class: className,
        contentClass = $bindable('*:border-0 flex flex-col border-box mt-2 w-56 rounded-md bg-[#F0F0F2] dark:bg-[#3E3E55] shadow-lg ring-1 ring-black/5 focus:outline-hidden'),
        ...rest
    }: ContentProps = $props();

    // --- Context ---
    const { _state, _class } = getDropdownCtx();

    // Setup Content's class
    let contentCls = $derived(cn(contentClass, _class.contentClass, _class.classContent, className));

</script>

{#if _state.active}
    <div bind:this={_state.content_reference} class={ contentCls } {...rest}>
        {@render children?.()}
    </div>
{/if}

<!--@component
    Generated by SvelteForge🔥

    @file DropdownContent.svelte
    @description
    Container for dropdown content, shown only when the dropdown is active. Pulls visibility state
    and styling from context.

    @props
    Extends `HTMLAttributes<HTMLDivElement>`. Main props:
    - `contentClass`: Local class for this container.
    - `class`: Native Svelte `class` also accepted and merged.

    @context
    Pulls from dropdown context:
    - `_state.active`: Controls visibility.
    - `_state.content_reference`: Used for click-outside detection.
    - `_class.contentClass`, `_class.classContent`: Inherited styles from `Dropdown.Menu`.

    @rendered
    Only renders when `_state.active` is true. Uses a single `<div>` with merged classes and reference binding.

    @usage
    Nest this inside `Dropdown.Menu`, wrapping your dropdown items:

    ```svelte
    <Dropdown.Content>
        <Dropdown.Button href="/settings">Settings</Dropdown.Button>
        <Dropdown.Divider />
        <Dropdown.Button on:click={logout}>Logout</Dropdown.Button>
    </Dropdown.Content>
    ```
-->