<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { DividerProps } from ".."
	import { getDropdownCtx } from '../ctx.svelte';
    
    let {
        children,
        class: className,
        dividerClass = $bindable('w-full h-[1px]'),
        ...rest
    }: DividerProps = $props();

    // --- Context ---
    const {_class} = getDropdownCtx()

    // Setup Divider's class
    let dividerCls = $derived(cn(dividerClass, _class.dividerClass, _class.classDivider, className));

</script>

<hr class={dividerCls} {...rest}/>

<!--@component
    Generated by SvelteForge🔥

    @file DropdownDivider.svelte
    @description
    A horizontal rule used to separate dropdown sections visually. Automatically styled through dropdown context.

    @props
    Extends `HTMLAttributes<HTMLDivElement>`. Accepts:
    - `dividerClass`: Specific class to style this divider instance.
    - `class`: Additional class merged in.

    @context
    Pulls from dropdown context:
    - `_class.dividerClass`, `_class.classDivider`: Base and user-defined divider styles.

    @rendered
    Outputs a single `<hr>` with the combined classes and props.

    @usage
    Use it to split up logical sections in dropdowns:

    ```svelte
    <Dropdown.Content>
        <Dropdown.Button>Account</Dropdown.Button>
        <Dropdown.Divider />
        <Dropdown.Button>Logout</Dropdown.Button>
    </Dropdown.Content>
    ```
-->