<script lang="ts">

	// === Core ===
	import { cn } from '@utils';

	// === Components ===
	import { Flex } from 'sk-clib';
	import { Dropdown } from '@components';

	// === Icons ===
	import IconDark from '~icons/ic/round-dark-mode';
	import IconLight from '~icons/ic/round-light-mode';

	// === State ===
	import { global_theme$ } from '@state';
	import type { Props } from '..';

	let {
		class: className,
		lightdarkClass = $bindable('')
	}: Props = $props();

	
	// Setup LightDark's Class
	let lightdarkCls = $derived(cn(lightdarkClass, className))
</script>

<Dropdown.Menu class={lightdarkCls}>
	<Dropdown.Trigger>
		<Dropdown.Button class="w-fit rounded-md">Theme</Dropdown.Button>
	</Dropdown.Trigger>

	<Dropdown.Content class="w-36">
		<Dropdown.Button onclick={() => global_theme$.set("light")}>
			<Flex class="items-center pl-6 gap-1">
				<IconLight />
                Light
			</Flex>
		</Dropdown.Button>

		<Dropdown.Divider/>

		<Dropdown.Button onclick={() => global_theme$.set("dark")}>
			<Flex class="items-center pl-6 gap-1">
				<IconDark/>
                Dark
			</Flex>
		</Dropdown.Button>
	</Dropdown.Content>
</Dropdown.Menu>

<!--@component
    Created by Amaan Dhanani
    - Uses the `Dropdown` component generated by SvelteForge🔥 (imported through `"src/lib/components"`)
    - Depends on `"./mode.ts"` developed by GitHub user TreltaSev
    - Subject to changes based on future updates by TreltaSev and Amaan Dhanani

    @file LightDark.svelte
    @description
    A dropdown menu for toggling between light and dark mode using Tailwind CSS.
    The component is styled using contextual classes from the `Dropdown` component.

    @props
    - `className`: Additional Tailwind utility classes passed in.

    @rendered
    Renders a dropdown that allows switching between light and dark themes.

    @usage

    ```svelte
    <LightDark className="px-10" />
    ```
-->