[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "backend"
version = "0.1.0"
description = "FastAPI backend package"
requires-python = ">=3.11"
authors = [{ name="TreltaSev "}]
dependencies = [
    "fastapi==0.116.1",
    "uvicorn==0.35.0"
]


[tool.hatch.build.targets.wheel]
packages = [
    { include = "utils", from = "src" }
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["utils*"]