<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { Props } from ".."
	import { setStepsCtx } from '../ctx.svelte';    
	import type { Step } from '../types';
	import type { Component, Snippet } from 'svelte';
    
    let {
        children,
        class: className,
        stepsClass = $bindable(''),
        steps = $bindable([]),
        step = $bindable(0),
        helper = $bindable(undefined),
        ...rest
    }: Props = $props();

    // Setup Steps's class
    let stepsCls = $state(cn(stepsClass, className));
    $effect(() => {
        stepsCls = cn(stepsClass, className)
    })

    const {_ctx} = setStepsCtx();
    _ctx.steps = steps

    $effect(() => {
        step = _ctx.step
        helper = _ctx.helpers
    })

    let StepComponent: Component | undefined = $derived(_ctx.steps[_ctx.step].component)

</script>

<div class={ stepsCls } {...rest}>
    <StepComponent/>
</div>

<!--@component
    Generated by SvelteForge🔥
-->

